name: mitumba_ui
description: Mitumba design system for Flutter — reusable widgets for Kenya's second-hand fashion marketplace.
version: 0.0.1
homepage: https://mitumba.stanl.ink
publisher: mitumba.stanl.ink
repository: https://github.com/Mitumba-Ltd/mitumba-flutter-ui
issue_tracker: https://github.com/Mitumba-Ltd/mitumba-flutter-ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook: ^3.23.0

flutter:
  uses-material-design: true
