name: widgetbook_mitumba_ui
description: Widgetbook for mitumba_ui design system.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.23.0
  mitumba_ui:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
